### PR TITLE
fix parsing of newline in RAW-LINE

### PR DESCRIPTION
**Pull request by melisgl**
Previously, carriage return characters were not allowed in RAW-LINE. Since NEWLINE tested for linefeed or carriage return plus linefeed, this resulted in carriage return characters without a following linefeed causing havoc. See the added test.

### CODE REVIEW

**Comment by melisgl** [comment]
This pull request now has fixes for #58, #59 and #60.

**Comment by 3b** [comment]
will try to get to this soon, when i have more time to think about it. Looks reasonable from a quick skim though, aside from I'd probably name the `*chars-to-escape...` vars as `*inline-chars-to-escape*` and `*block-chars-to-escape*` or similar.

I think there may be a few more edge cases to deal with to support other blocks correctly, though I'll probably merge this first either way.

In particular I wonder about horizontal rules (`---` `* * *` `- - - - -` etc..), setext headers (also `---` depending on context, and `====` etc), and numbered lists. Looks like numbered lists might work already since it preserves the `\` in the parse, and printing `\--` for `--` at beginning of the line might be OK since the extra `\` gets dropped on parse in that case, but needs more thought than i have time for now.

(If you want to work on it further before i get to it, might rebase onto the `rc` branch, so it can test against blocks with more complicated indentation as well.)

**Comment by melisgl** [comment]
Thanks. I'll rebase and see how it works.

**Comment by melisgl** [comment]
Well, I had to come back to this to fix escaping of < and &. It think commit fbd10755b087b63b23d778e382578feb20d1767c makes escaping correct for all special chars. It tries to use escapes economically, but utterly fails to do that with < and &. I guess, correctness first?

**Comment by 3b** [comment]
Doesn't look like I'll have any energy for poking at edge cases, and seems like current state of the PR is an improvement in general even if there are some remaining, so will merge it and think about it more if we run into any specific problems later.

**Pull request merged**
